products:
  - product_code: GR1
    name: Green Tea
    price: 3.11
  - product_code: SR1
    name: Strawberries
    price: 5.00
  - product_code: CF1
    name: Coffee
    price: 11.23
  - product_code: EGT1
    name: Earl Grey Tea
    price: 2.00